services:
  postgres:
    image: postgres:17-alpine
    container_name: noteapp-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: noteapp
      POSTGRES_PASSWORD: noteapp_password
      POSTGRES_DB: noteapp
    ports:
      - "5434:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
